vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        posts:
            uri_prefix: /images/posts
            upload_destination: '%kernel.project_dir%/public/images/posts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    #mappings: un mapping par champ d'upload
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
